/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as QuienesSomosRouteImport } from './routes/quienes-somos'
import { Route as PortafoliosRouteImport } from './routes/portafolios'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as InternacionalRouteImport } from './routes/internacional'
import { Route as FinancierosRouteImport } from './routes/financieros'
import { Route as AtencionRouteImport } from './routes/atencion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'

const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const QuienesSomosRoute = QuienesSomosRouteImport.update({
  id: '/quienes-somos',
  path: '/quienes-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafoliosRoute = PortafoliosRouteImport.update({
  id: '/portafolios',
  path: '/portafolios',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const InternacionalRoute = InternacionalRouteImport.update({
  id: '/internacional',
  path: '/internacional',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancierosRoute = FinancierosRouteImport.update({
  id: '/financieros',
  path: '/financieros',
  getParentRoute: () => rootRouteImport,
} as any)
const AtencionRoute = AtencionRouteImport.update({
  id: '/atencion',
  path: '/atencion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiciosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atencion': typeof AtencionRoute
  '/financieros': typeof FinancierosRoute
  '/internacional': typeof InternacionalRoute
  '/pagos': typeof PagosRoute
  '/portafolios': typeof PortafoliosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atencion': typeof AtencionRoute
  '/financieros': typeof FinancierosRoute
  '/internacional': typeof InternacionalRoute
  '/pagos': typeof PagosRoute
  '/portafolios': typeof PortafoliosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atencion': typeof AtencionRoute
  '/financieros': typeof FinancierosRoute
  '/internacional': typeof InternacionalRoute
  '/pagos': typeof PagosRoute
  '/portafolios': typeof PortafoliosRoute
  '/quienes-somos': typeof QuienesSomosRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/servicios/$slug': typeof ServiciosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atencion'
    | '/financieros'
    | '/internacional'
    | '/pagos'
    | '/portafolios'
    | '/quienes-somos'
    | '/servicios'
    | '/servicios/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atencion'
    | '/financieros'
    | '/internacional'
    | '/pagos'
    | '/portafolios'
    | '/quienes-somos'
    | '/servicios'
    | '/servicios/$slug'
  id:
    | '__root__'
    | '/'
    | '/atencion'
    | '/financieros'
    | '/internacional'
    | '/pagos'
    | '/portafolios'
    | '/quienes-somos'
    | '/servicios'
    | '/servicios/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtencionRoute: typeof AtencionRoute
  FinancierosRoute: typeof FinancierosRoute
  InternacionalRoute: typeof InternacionalRoute
  PagosRoute: typeof PagosRoute
  PortafoliosRoute: typeof PortafoliosRoute
  QuienesSomosRoute: typeof QuienesSomosRoute
  ServiciosRoute: typeof ServiciosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quienes-somos': {
      id: '/quienes-somos'
      path: '/quienes-somos'
      fullPath: '/quienes-somos'
      preLoaderRoute: typeof QuienesSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolios': {
      id: '/portafolios'
      path: '/portafolios'
      fullPath: '/portafolios'
      preLoaderRoute: typeof PortafoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internacional': {
      id: '/internacional'
      path: '/internacional'
      fullPath: '/internacional'
      preLoaderRoute: typeof InternacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financieros': {
      id: '/financieros'
      path: '/financieros'
      fullPath: '/financieros'
      preLoaderRoute: typeof FinancierosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atencion': {
      id: '/atencion'
      path: '/atencion'
      fullPath: '/atencion'
      preLoaderRoute: typeof AtencionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof ServiciosRoute
    }
  }
}

interface ServiciosRouteChildren {
  ServiciosSlugRoute: typeof ServiciosSlugRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosSlugRoute: ServiciosSlugRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtencionRoute: AtencionRoute,
  FinancierosRoute: FinancierosRoute,
  InternacionalRoute: InternacionalRoute,
  PagosRoute: PagosRoute,
  PortafoliosRoute: PortafoliosRoute,
  QuienesSomosRoute: QuienesSomosRoute,
  ServiciosRoute: ServiciosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
